name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare build environment
      run: |
        # Commands to generate the 'configure' script if necessary
        # Example: autoreconf -i
        autoreconf -i

    - name: Run configure script
      run: ./configure

    - name: Build
      run: make
      
